spring.application.name=Portafolio
spring.datasource.url=jdbc:postgresql://localhost:5432/portafolio
spring.datasource.username=postgres
spring.datasource.password=020131

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# Internationalization (i18n)
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.web.locale=es_ES

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.sql-migration-prefix=V
spring.flyway.sql-migration-separator=__
spring.flyway.sql-migration-suffixes=.sql

# JavaMail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-email@gmail.com
spring.mail.password=tu-password-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.from=noreply@portafolio.com

# App Configuration
app.owner.email=tu-email@ejemplo.com

# Server
server.port=8080
server.servlet.context-path=/
